### PR TITLE
Add Python 3 compatiblity for get_call_data

### PR DESCRIPTION
**Pull request by miohtama**
### What was wrong?

Binary data was expanded to unicode strings before merging.

### How was it fixed?

Don't use string formatting when dealing with binary data.

#### Cute Animal Picture

Mr. Mikko doing diving

### CODE REVIEW

**Comment by pipermerriam** [comment]
Test failures are unrelated and known problem.  Thanks for the patch

**Comment by pipermerriam** [comment]
I will likely be a bit delayed in getting a release out with this in it.  I need to get the test suite running happily first.

**Comment by miohtama** [comment]
No rush. There are few other things (10+) broken with Python 3. This is just a first little step towards compatibility.

**Comment by miohtama** [comment]
Would it be ok to open a python3 branch on github and have Python 2.7 + Python 3.5 setup for Travis there? Then gradually merge patches there until all tests pass.

**Pull request merged**
