### PR TITLE
Migrations

### PR DESCRIPTION
**Pull request by pipermerriam**
Work in progress for #106 

TODO list

- [ ] disect the various `Operation` classes so that they aren't single method giants
- [x] contract library linking
- [x] figure out better way to do receipts and writing them to the registrar
- [x] figure out how to use the registrar for things like "Where is contract X".
- [x] Actual filesystem stuff for migration files.
- [x] Gas estimates should move down into the `web3.eth.contract.deploy()` and `web3.eth.contract.transact()` methods. (https://github.com/pipermerriam/web3.py/pull/53)
- [ ] Implement `populus.chain.Chain` class for use when the user wants to run their own blockchain client.
- [x] Implement `populus migrate` command.
- [x] Update deploy command to make use of migration utils.
- [ ] Update deploy command to link against already deployed instances of necessary libraries that are found in the registrar.
- [x] Redo `populus.migrations.writer` so that it handles imports.  This is likely changing the semantics of how writing works so that there is a serialization step, followed by a writing the actual migration contents.
- [ ] Extract duplicate code in `migrate` and `deploy` into a helper that is well tested. (pick chain, pick account, unlock account, write new defaults).
- [ ] Figure out if the `PopulusConfig` object in the pytest plugins is necessary.  I suspect that everything it does is now handled by the `Project` and `project.config` stuff.
- [ ] Write test coverage for pytest plugins.
- [ ] Update documentation for deployment
- [ ] Write documentation for migrations
- [ ] Update documentation for `populus chain run`
- [ ] Update documentation for pytest plugins.
- [ ] Write documentation for `populus.chain.Chain` objects
- [ ] Write documentation for `populus.project.Project` object
- [ ] Write documentation for project configuration

### What was wrong?

TODO

### How was it fixed?

TODO

#### Cute Animal Picture

> put a cute animal picture here.

TODO

### CODE REVIEW

**Comment by pipermerriam** [comment]
Currently, this is what a migration file is likely to look like.

```python
from populus import migrations


class Migration(migrations.Migration):
    migration_id = '0001_initial'
    dependencies = []

    operations = [
        migrations.DeployContract('Thrower', ['some-constructor-argument']),
    ]

    contract_data = {
        'Thrower': {
            'code': "0x606060405260405160208060318339506080604052518015601e576002565b50600680602b6000396000f3606060405200",
            'code_runtime': "0x606060405200",
            'abi': [
                {
                    "inputs": [{"name": "shouldThrow", "type": "bool"}],
                    "type": "constructor",
                },
            ],
        },
    }
```

**Comment by pipermerriam** [comment]
@miohtama curious whether you have a minute to look this over and give any preliminary feedback you might have on it.

**Comment by miohtama** [comment]
Can you give me links to existing migration frameworks and some background story? I know the concept of database migrations from SQLAlchemy, Django, etc. and I am curious if we are using the word migration in similar context here.

**Comment by pipermerriam** [comment]
I stole the concept from truffle so you can see their implementation in the
truffle documentation. Also I plan to implement a migration contract to
keep track of migration state and a registrar contract to keep track of
already deployed contract addresses.

**Comment by miohtama** [comment]
Perfect! Learning registrar contracts is one thing on my TODO list.

**Comment by pipermerriam** [comment]
@miohtama this is the initial version I hammered out last night.  It's really more of an immutable key/value store than a registrar.  The idea is as follows.

In migration `0002_deploy_Math_contract` which deploys some contract named `Math`, the Migration would register the following information within the registrar contract.

```
registrar.set('0002_deploy_Math_contract:operation-1:transaction-hash', '0x1234abcd')
registrar.set('0002_deploy_Math_contract:operation-1:contract-address', '0xabcd6789')
```

Then, future migrations could reference this value something like the following.

```
class Migration(migrations.Migration):
    ...
    operations = [
        migrations.SendTransaction({
            'from': '0x1234abcd',
            'to': migrations.RegistrarValue('0002_deploy_Math_contract:operation-1:contract-address`, type='address'),
        })
    ]
```

Then, within the execution of the `SendTransaction` operation, it would attempt to resolve the value associated with this key and use it as the `to` destination for this transaction.

**Pull request merged**
