### PR TITLE
Withoutast

### PR DESCRIPTION
**Pull request by euri10**
### What was wrong?
solidity fails with error -11 with the ast flag, by default py-solc put all values, this enable to remove a flag

### How was it fixed?
adding the -r flag here and changing py-solc, see https://github.com/pipermerriam/py-solc/pull/4

#### Cute Animal Picture

image

### CODE REVIEW

**Comment by pipermerriam** [comment]
ok, I think I'd prefer one of the following approaches if you're willing to rework this.

Rather than *removal* I think allowing explicit declaration of what should be passed into the `--combined-json` flag would be better, since it may not be obvious what can/should be removed.  This would look something like `populus compile --combined-json="bin,bin-runtime,abi"`.

An alternate approach that might be better would be to just add a `--solc-overrides` option that would be *intelligently* parsed into the appropriate `**compiler_kwargs` to be passed into the compiler commands.

I believe both of these approaches remove the need to make a downstream change to `py-solc`.

Thoughts?

**Comment by euri10** [comment]
i like the alternate approach more and I' ready to try to change it, that said there are a few things I'm note sure about

> since it may not be obvious what can/should be removed
`type=click.Choice(ALL_OUTPUT_VALUES)` enforces no 'wrong' option is passed, the only issue is that so far you can remove only one flag in the ALL_OUTPUT_VALUES passed 

I don't see how you can avoid changing py-solc as it passes by default ALL_OUTPUT_VALUES in
```
def compile_files(source_files, output_values=ALL_OUTPUT_VALUES, **kwargs):
...
...
combined_json = ','.join(output_values)
```

**Comment by pipermerriam** [comment]
So in order to change this in populus without requiring an upstream change would involve changing this line

https://github.com/pipermerriam/populus/blob/master/populus/cli/compile_cmd.py#L48

```
# populus/cli/compile_cmd.py#L48
result = compile_and_write_contracts(project_dir, optimize=optimize)
# should be changed to.

result = compile_and_write_contracts(project_dir, optimize=optimize, output_values=['bin', 'bin-runtime', 'abi'])
```

Since populus only really uses these values we can probably just hard code them here without problem.

**Comment by pipermerriam** [comment]
@euri10 can you see if https://github.com/pipermerriam/populus/pull/115 fixes your issue?  I realized this morning that there's a very simple solution to this and that a new flag is actually not really necessary (nor do I think it's useful since `populus` always wants just those three values to be in the combined json.)

**Comment by pipermerriam** [comment]
If it does I'd like to close this in favor of merging the upstream version.

**Pull request closed without merging**
