### PR TITLE
Adding chain run opts & Workflow Documentation 

### PR DESCRIPTION
**Pull request by RCL-Carl**
Hi, 

This pull request contains a small addition to the "chain run" command to add a verbosity flag for passing to geth. I've found this really useful to running down issues. 

I've also add a section to the Overview documentation that does a small walk through of using the workflow for using populus. It isn't extensive but at least provides a starting point.

### CODE REVIEW

**Comment by pipermerriam** [comment]
This looks great.  It is however missing a [cute animal picture](https://github.com/pipermerriam/populus/blob/master/CONTRIBUTING.md#cute-animal-pictures) :stuck_out_tongue_winking_eye: 

I'll get this merged and released early tomorrow.  Thanks so much for this great contribution.

**Comment by RCL-Carl** [comment]
Like - do you want the picture in the commit ? or a link in the message? Hopefully this will suffice: 
Pangolin

**Comment by pipermerriam** [comment]
I love it.

**Comment by pipermerriam** [comment]
@RCL-Carl you can grab this in the 0.6.2 release.  Thanks again for your contribution.

**Comment by RCL-Carl** [comment]
Sure - probably won't be until this evening though.

**Pull request merged**
