### PR TITLE
[do not merge] First attempt to make pytest run under Python 3. Document some testin…

### PR DESCRIPTION
**Pull request by miohtama**
This is a first attempt to make tests run under Python 3.

* It contains updated on documentation how test fixtures should be used

* It contains updates across the codebase to fix Python 3 compatibility issues, mostly implicit use of byte strings

I opened this pull request to track the progress. However I believe travis should be fixed first, so that we can make sure the eventual merge will happen in pain free manner.

### CODE REVIEW

**Comment by pipermerriam** [comment]
👍  thanks for starting this work.

**Comment by pipermerriam** [comment]
The documentation included here is great.  Would you be willing to re-work this against the updated master branch?  I think all of the code changes you have provided are no longer valid.  The documentation you wrote would be a great addition.  It will need to be reworked a bit since many of the underlying API's have changed, but the overall structure of it should still fit nicely.

**Comment by miohtama** [comment]
I will rework against 1.0.0. Also some more documentation bits coming in.

**Comment by miohtama** [comment]
1.0.0 is ready to go?

**Comment by pipermerriam** [comment]
@miohtama `1.0.0b1` is released on pypi.  I'm planning on iterating through a few beta releases to try and shake out any bugs that may be present.  Lots of code changes and I guarantee I fat-fingered something.

**Comment by miohtama** [comment]
Ok, I'll start rebasing against 1.0.0 tonight.

**Comment by miohtama** [comment]
Looks superb work.

**Pull request closed without merging**
